### ISSUE TITLE
Learn about JSON

### ISSUE THREAD

**Issue by afg419** [afg419/traffic-spy#3]

**Comment by Tman22** [comment]
JSON (JavaScript Object Notation)

JSON is a lightweight data-interchange format.. AKA it makes it easy to read and right / easy for machines to parse. 

Built on 2 universally available structures:
    1. Collection of name/value pairs. Often referred to as object (HASH?)
    2. Ordered list of values. More commonly called an array /vector

Likely to use Instant Methods: 

PARSE:
puts my_hash["hello"] => "goodbye"  
JSON.parse('{"hello": "goodbye"}')
    NOTICE EXTRA QUOTES: RUBY EXPECTS TO SEE A STRING.

GENERATE :
my_hash = {:hello => "goodbye"}
JSON.generate(my_hash) => “{\"hello\":\"goodbye\"}"
OR puts {:hello => "goodbye"}.to_json
